name: "Test in nix"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            system-features = nixos-test benchmark big-parallel kvm
            extra-substituters = https://tezos.nix-cache.workers.dev
            extra-trusted-public-keys = tezos-nix-cache.marigold.dev-1:4nS7FPPQPKJIaNQcbwzN6m7kylv16UCWWgjeZZr2wXA=
      - name: Set up signing key
        shell: bash
        run: |
          echo $CACHE_PRIV_KEY > ./nix-cache-key.sec
          sudo mv ./nix-cache-key.sec /etc/nix/nix-cache-key.sec
          ./.github/workflows/list-nix-store.sh > ~/.nix-store-paths
          mkdir -p ~/.aws && touch ~/.aws/credentials
          cat <<EOF >> ~/.aws/credentials
            [default]
            aws_access_key_id = $AWS_ACCESS_KEY_ID
            aws_secret_access_key = $AWS_SECRET_ACCESS_KEY
          EOF
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CI_USER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_USER_AWS_SECRET_ACCESS_KEY }}
          CACHE_PRIV_KEY: ${{ secrets.CACHE_PRIV_KEY }}

      - name: "Run nix flake check"
        run: nix flake check
      - name: "Check formatting"
        run: nix fmt -- --check flake.nix ./nix/*

      - name: Build default
        run: nix --log-format raw -L build .#

      - name: Upload to cache
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CI_USER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_USER_AWS_SECRET_ACCESS_KEY }}
          CACHE_PRIV_KEY: ${{ secrets.CACHE_PRIV_KEY }}
          CACHE_ENDPOINT: ${{ secrets.CACHE_ENDPOINT }}
        run: ./.github/workflows/upload-to-cache.sh $CACHE_ENDPOINT
      - name: "Build client"
        run: nix --log-format raw -L build .#tezos-client

      - name: Upload to cache
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CI_USER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_USER_AWS_SECRET_ACCESS_KEY }}
          CACHE_PRIV_KEY: ${{ secrets.CACHE_PRIV_KEY }}
          CACHE_ENDPOINT: ${{ secrets.CACHE_ENDPOINT }}
        run: ./.github/workflows/upload-to-cache.sh $CACHE_ENDPOINT
      - name: "Build node"
        run: nix --log-format raw -L build .#tezos-node

      - name: Upload to cache
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CI_USER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_USER_AWS_SECRET_ACCESS_KEY }}
          CACHE_PRIV_KEY: ${{ secrets.CACHE_PRIV_KEY }}
          CACHE_ENDPOINT: ${{ secrets.CACHE_ENDPOINT }}
        run: ./.github/workflows/upload-to-cache.sh $CACHE_ENDPOINT
      - name: "Build baker-alpha"
        run: nix --log-format raw -L build .#tezos-baker-alpha    

      - name: Upload to cache
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CI_USER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_USER_AWS_SECRET_ACCESS_KEY }}
          CACHE_PRIV_KEY: ${{ secrets.CACHE_PRIV_KEY }}
          CACHE_ENDPOINT: ${{ secrets.CACHE_ENDPOINT }}
        run: ./.github/workflows/upload-to-cache.sh $CACHE_ENDPOINT                                                                           
      - name: "Build rollup-node-alpha"
        run: nix --log-format raw -L build .#tezos-tx-rollup-node-alpha

      - name: Upload to cache
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CI_USER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_USER_AWS_SECRET_ACCESS_KEY }}
          CACHE_PRIV_KEY: ${{ secrets.CACHE_PRIV_KEY }}
          CACHE_ENDPOINT: ${{ secrets.CACHE_ENDPOINT }}
        run: ./.github/workflows/upload-to-cache.sh $CACHE_ENDPOINT
      - name: "Build trunk-client"
        run: nix --log-format raw -L build .#trunk-tezos-client

      - name: Upload to cache
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CI_USER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_USER_AWS_SECRET_ACCESS_KEY }}
          CACHE_PRIV_KEY: ${{ secrets.CACHE_PRIV_KEY }}
          CACHE_ENDPOINT: ${{ secrets.CACHE_ENDPOINT }}
        run: ./.github/workflows/upload-to-cache.sh $CACHE_ENDPOINT
      - name: "Build trunk-node"
        run: nix --log-format raw -L build .#trunk-tezos-node

      - name: Upload to cache
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CI_USER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_USER_AWS_SECRET_ACCESS_KEY }}
          CACHE_PRIV_KEY: ${{ secrets.CACHE_PRIV_KEY }}
          CACHE_ENDPOINT: ${{ secrets.CACHE_ENDPOINT }}
        run: ./.github/workflows/upload-to-cache.sh $CACHE_ENDPOINT
      - name: "Build trunk-baker-alpha"
        run: nix --log-format raw -L build .#trunk-tezos-baker-alpha

      - name: Upload to cache
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CI_USER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_USER_AWS_SECRET_ACCESS_KEY }}
          CACHE_PRIV_KEY: ${{ secrets.CACHE_PRIV_KEY }}
          CACHE_ENDPOINT: ${{ secrets.CACHE_ENDPOINT }}
        run: ./.github/workflows/upload-to-cache.sh $CACHE_ENDPOINT
      - name: "Build trunk-rollup-node-alpha"
        run: nix --log-format raw -L build .#trunk-tezos-tx-rollup-node-alpha

      - name: Upload to cache
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CI_USER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_USER_AWS_SECRET_ACCESS_KEY }}
          CACHE_PRIV_KEY: ${{ secrets.CACHE_PRIV_KEY }}
          CACHE_ENDPOINT: ${{ secrets.CACHE_ENDPOINT }}
        run: ./.github/workflows/upload-to-cache.sh $CACHE_ENDPOINT
