name: "Test in nix"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            system-features = nixos-test benchmark big-parallel kvm
            extra-substituters = https://tezos.nix-cache.workers.dev
            extra-trusted-public-keys = tezos-nix-cache.marigold.dev-1:4nS7FPPQPKJIaNQcbwzN6m7kylv16UCWWgjeZZr2wXA=

      - uses: ulrikstrid/nix-s3-action@fork
        with:
          endpoint: "s3://tezos-nix?endpoint=https://7a53c28e9b7a91239f9ed42da04276bc.r2.cloudflarestorage.com/tezos-nix"
          signingKey: ${{ secrets.CACHE_PRIV_KEY }}
          awsAccessKeyId: ${{ secrets.CI_USER_AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.CI_USER_AWS_SECRET_ACCESS_KEY }}

      - name: "Run nix flake check"
        run: |
          export NIXPKGS_ALLOW_BROKEN=1
          nix flake check --impure
      - name: "Check formatting"
        run: nix fmt --accept-flake-config -- --fail-on-change
      - name: "Lint"
        run: nix run nixpkgs#statix -- check

      - name: "Build client"
        run: nix --log-format raw -L build --accept-flake-config .#octez-client
      - name: "Build codec"
        run: nix --log-format raw -L build --accept-flake-config .#octez-codec
      - name: "Build octez-dal-node"
        run: nix --log-format raw -L build --accept-flake-config .#octez-dal-node
      - name: "Build node"
        run: nix --log-format raw -L build --accept-flake-config .#octez-node
      - name: "Build node"
        run: nix --log-format raw -L build --accept-flake-config .#octez-proxy-server
      - name: "Build node"
        run: nix --log-format raw -L build --accept-flake-config .#octez-signer
      - name: "Build octez-snoop"
        run: nix --log-format raw -L build --accept-flake-config .#octez-snoop
      - name: "Build tezos-tps-evaluation"
        run: nix --log-format raw -L build --accept-flake-config .#tezos-tps-evaluation
      - name: "Build octez-smart-rollup-wasm-debugger"
        run: nix --log-format raw -L build --accept-flake-config .#octez-smart-rollup-wasm-debugger
      - name: "Build accuser-alpha"
        run: nix --log-format raw -L build --accept-flake-config .#octez-accuser-alpha
      - name: "Build baker-alpha"
        run: nix --log-format raw -L build --accept-flake-config .#octez-baker-alpha
      - name: "Build smart-rollup-client-alpha"
        run: nix --log-format raw -L build --accept-flake-config .#octez-smart-rollup-client-alpha
      - name: "Build smart-rollup-node-alpha"
        run: nix --log-format raw -L build --accept-flake-config .#octez-smart-rollup-node-alpha
      - name: "Build accuser-PtMumbai"
        run: nix --log-format raw -L build --accept-flake-config .#octez-accuser-PtMumbai
      - name: "Build baker-PtMumbai"
        run: nix --log-format raw -L build --accept-flake-config .#octez-baker-PtMumbai
      - name: "Build smart-rollup-client-PtMumbai"
        run: nix --log-format raw -L build --accept-flake-config .#octez-smart-rollup-client-PtMumbai
      - name: "Build smart-rollup-node-PtMumbai"
        run: nix --log-format raw -L build --accept-flake-config .#octez-smart-rollup-node-PtMumbai
  trunk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            system-features = nixos-test benchmark big-parallel kvm
            extra-substituters = https://tezos.nix-cache.workers.dev
            extra-trusted-public-keys = tezos-nix-cache.marigold.dev-1:4nS7FPPQPKJIaNQcbwzN6m7kylv16UCWWgjeZZr2wXA=

      - uses: ulrikstrid/nix-s3-action@fork
        with:
          endpoint: "s3://tezos-nix?endpoint=https://7a53c28e9b7a91239f9ed42da04276bc.r2.cloudflarestorage.com/tezos-nix"
          signingKey: ${{ secrets.CACHE_PRIV_KEY }}
          awsAccessKeyId: ${{ secrets.CI_USER_AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.CI_USER_AWS_SECRET_ACCESS_KEY }}

      - name: "Build client"
        run: nix --log-format raw -L build --accept-flake-config .#trunk-octez-client
      - name: "Build codec"
        run: nix --log-format raw -L build --accept-flake-config .#trunk-octez-codec
      - name: "Build octez-dal-node"
        run: nix --log-format raw -L build --accept-flake-config .#trunk-octez-dal-node
      - name: "Build node"
        run: nix --log-format raw -L build --accept-flake-config .#trunk-octez-node
      - name: "Build node"
        run: nix --log-format raw -L build --accept-flake-config .#trunk-octez-proxy-server
      - name: "Build node"
        run: nix --log-format raw -L build --accept-flake-config .#trunk-octez-signer
      - name: "Build octez-snoop"
        run: nix --log-format raw -L build --accept-flake-config .#trunk-octez-snoop
      - name: "Build tezos-tps-evaluation"
        run: nix --log-format raw -L build --accept-flake-config .#trunk-tezos-tps-evaluation
      - name: "Build octez-smart-rollup-wasm-debugger"
        run: nix --log-format raw -L build --accept-flake-config .#trunk-octez-smart-rollup-wasm-debugger
      - name: "Build accuser-alpha"
        run: nix --log-format raw -L build --accept-flake-config .#trunk-octez-accuser-alpha
      - name: "Build baker-alpha"
        run: nix --log-format raw -L build --accept-flake-config .#trunk-octez-baker-alpha
      - name: "Build smart-rollup-client-alpha"
        run: nix --log-format raw -L build --accept-flake-config .#trunk-octez-smart-rollup-client-alpha
      - name: "Build smart-rollup-node-alpha"
        run: nix --log-format raw -L build --accept-flake-config .#trunk-octez-smart-rollup-node-alpha
      - name: "Build accuser-PtMumbai"
        run: nix --log-format raw -L build --accept-flake-config .#trunk-octez-accuser-PtMumbai
      - name: "Build baker-PtMumbai"
        run: nix --log-format raw -L build --accept-flake-config .#trunk-octez-baker-PtMumbai
      - name: "Build smart-rollup-client-PtMumbai"
        run: nix --log-format raw -L build --accept-flake-config .#trunk-octez-smart-rollup-client-PtMumbai
      - name: "Build smart-rollup-node-PtMumbai"
        run: nix --log-format raw -L build --accept-flake-config .#trunk-octez-smart-rollup-node-PtMumbai
