name: "Test in nix"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            system-features = nixos-test benchmark big-parallel kvm
            extra-substituters = https://tezos.nix-cache.workers.dev
            extra-trusted-public-keys = tezos-nix-cache.marigold.dev-1:4nS7FPPQPKJIaNQcbwzN6m7kylv16UCWWgjeZZr2wXA=

      - uses: ulrikstrid/nix-s3-action@fork
        with:
          endpoint: "s3://tezos-nix?endpoint=https://7a53c28e9b7a91239f9ed42da04276bc.r2.cloudflarestorage.com/tezos-nix"
          signingKey: ${{ secrets.CACHE_PRIV_KEY }}
          awsAccessKeyId: ${{ secrets.CI_USER_AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.CI_USER_AWS_SECRET_ACCESS_KEY }}

      - name: "Run nix flake check"
        run: |
          export NIXPKGS_ALLOW_BROKEN=1
          nix flake check --impure
      - name: "Check formatting"
        run: nix fmt --accept-flake-config -- --fail-on-change
      - name: "Lint"
        run: nix run nixpkgs#statix -- check

      - name: Build default
        run: nix --log-format raw -L build --accept-flake-config .#
      - name: "Build client"
        run: nix --log-format raw -L build --accept-flake-config .#octez-client
      - name: "Build node"
        run: nix --log-format raw -L build --accept-flake-config .#octez-node
      - name: "Build baker-alpha"
        run: nix --log-format raw -L build --accept-flake-config .#octez-baker-alpha
      - name: "Build trunk-client"
        run: nix --log-format raw -L build --accept-flake-config .#trunk-octez-client
        continue-on-error: true
      - name: "Build trunk-node"
        run: nix --log-format raw -L build --accept-flake-config .#trunk-octez-node
        continue-on-error: true
      - name: "Build trunk-baker-alpha"
        run: nix --log-format raw -L build --accept-flake-config .#trunk-octez-baker-alpha
        continue-on-error: true
      - name: "Build trunk-octez-dal-node"
        run: nix --log-format raw -L build --accept-flake-config .#trunk-octez-dal-node
        continue-on-error: true
