name: "Test in nix"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
      - uses: cachix/cachix-action@v10
        with:
          name: anmonteiro
      - name: "Run nix flake check"
        run: nix flake check
      - name: "Unit tests"
        run: nix develop -c dune build @runtest --force --no-buffer
